= Introduction

We gratefully accept contributions via
https://help.github.com/articles/about-pull-requests/[pull requests].

Use the issue tracker to suggest feature requests, report bugs, and ask questions.
This is also a great way to connect with the developers of the project as well
as others who are interested in this solution.

== Changing the code-base

Generally speaking, you should fork this repository, make changes in your
own fork, and then submit a pull-request. This is often called the https://gist.github.com/Chaser324/ce0505fbed06b947d962[Fork-and-Pull model] 

* All contributions to this project will be released under the inbound=outbound norm, that is,
 they are submitted under the projects main license.
* By submitting a pull request or filing a bug, issue, or
 feature request, you agree to comply with this waiver of copyright interest.
 Details can be found in the link:./LICENSE[LICENSE].
* All new code should have associated unit tests in some form.

=== Signoff and optionally Sign each Commit

As part of filing a pull request you agree to the DCO.
https://developercertificate.org/[Developer Certificate of Origin] 

A DCO is a lightweight way for a contributor to confirm that they wrote or otherwise have the right
to submit code or documentation to a project. 

To confirm that you agree to the DCO, you need to *sign off* your commits when sending us a pull request. Technically, this is done by supplying the `-s`/`--signoff` flag to git when committing:

`$ git commit -s -m "add fix for the bug"`

Optionally, you can also sign the commit with `-S` which also gives your commit a nice verified button on GitHub,
It requires that you have a GPG keypair set up, see https://docs.github.com/en/github/authenticating-to-github/signing-commits[Sign commit on GitHub with GPG key]


`$ git commit -s -S -m "add fix for the bug"`

For the difference between signoff and signing, see
https://medium.com/@MarkEmeis/git-commit-signoff-vs-signing-9f37ee272b14/[Git signoff vs signing]

== Git History

* We prefer you follow the Conventional Commit standard: https://www.conventionalcommits.org

Happy contributing!
