name: Renovate Validation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  renovate-validation:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Validate Renovate Config
      run: npx -y --package renovate@latest -- renovate-config-validator renovate.json
