---
name: 'Self scan'
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  self_scan:
    name: Self scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check file permissions
        run: |
          ls -la
          id
      - uses: ./
